apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.auth.name }}-config"
data:
  PORT: "{{ .Values.auth.port.http }}"
  JWT_SECRET: "{{ .Values.auth.jwt.secret }}"
  JWT_EXPIRES_IN: "{{ .Values.auth.jwt.expirationMs }}"
  AUTH_GRPC_SERVICE_URL: "0.0.0.0:{{ .Values.auth.port.grpc }}"
