{{- if .Values.jobs.enabled}}
apiVersion: v1
kind: Deployment
metadata:
  name: {{ .Values.jobs.name}}
  labels:
    app: {{ .Values.jobs.name}}
spec:
  replicas: {{ .Values.jobs.replicas}}
  selector: 
    matchLabels:
      app: {{ .Values.jobs.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.jobs.name}}
    spec:
      containers:
        - name: {{ .Values.jobs.name}}
          image: {{ .Values.jobs.image}}
          imagePullPolicy: {{ .Values.global.imagePullPolicy}}
          volumeMounts:
            - name: {{ .Values.jobs.volumes.name}}
              mountPath: /apps/jobs/uploads
          ports:
            - containerPort: {{ .Values.jobs.port}}
          env:
            {{- include "common.env" . | nindent 12}}
            - name: PORT
              value: {{ .Values.jobs.port }}
            - name: AUTH_GRPC_SERVICE_URL
              value: "{{ .Values.jobs.grpcAuthService}}"
      volumes:
        - name: {{ .Values.jobs.volumes.name}}
        persistentVolumeClaim:
          claimName: volume-pvc
      

{{- end}}