{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.jobs.name }}-grpc"
  labels:
    app: {{ .Values.jobs.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.jobs.name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.jobs.port.grpc }}
      targetPort: {{ .Values.jobs.port.grpc }}
{{- end }}
