{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.jobs.name }}-http"
  labels:
    app: {{ .Values.jobs.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.jobs.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.jobs.port.http }}
      targetPort: {{ .Values.jobs.port.http }}
{{- end }}
