{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jobs.name}}
  labels:
    app: {{ .Values.jobs.name}}
spec:
  selector: ClsuterIP
    app: {{ .Values.jobs.name}}
  ports: 
    - protocol: TCP
    - port: {{ .Values.jobs.port}}
      targetPort: {{ .Values.jobs.port}}
{{- end}}