jobs:
  name: jobs
  enabled: true
  replicas: 1
  image: 493516932002.dkr.ecr.eu-central-1.amazonaws.com/jobs-generator/jobs:latest
  port: 3001
  grpcAuthService: "auth-grpc::5000"

executor:
  name: executor
  enabled: true
  replicas: 1
  image: 493516932002.dkr.ecr.eu-central-1.amazonaws.com/jobs-generator/executor:latest
  port: 3002

auth:
  name: auth
  enabled: true
  replicas: 1
  image: 493516932002.dkr.ecr.eu-central-1.amazonaws.com/jobs-generator/auth:latest
  port:
    http: 3000
    grpc: 5000
  jwt:
    secret: uyw4h5fo34875fto7t4o5f7q63o745foq374tdohq3t4o57dt3
    expirationMs: "28800000"

products:
  name: products
  enabled: true
  replicas: 1
  image: 493516932002.dkr.ecr.eu-central-1.amazonaws.com/jobs-generator/products:latest
  port:
    http: 3003
    grpc: 5001

global:
  imagePullPolicy: Always

pulsar:
  namespace: pulsar
  namespaceCreate: true
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    replicaCount: 1
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false
