{{- if .Values.auth.enabled }}
apiVersion: 'apps/v1'
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}
  labels:
    app: {{ .Values.auth.name }}
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.auth.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.name }}
    spec:
      initContainers:
        - name: prisma-migrate
          image: {{ .Values.auth.image }}
          imagePullPolicy: {{ .Values.global.imagePolicy }}
          command: ["sh", "-c"]
          args:
            - npx prisma migrate deploy --schema=apps/auth/prisma/schema.prisma
          env:
            {{- include "auth.env" . | nindent 12 }} # Separate env file

      containers:
        - name: {{ .Values.auth.name }}
          image: {{ .Values.auth.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.auth.port.http }}
            - containerPort: {{ .Values.auth.port.grpc }}
          env:
            {{- include "auth.env" . | nindent 12 }} # Use shared env file
{{- end }}
