{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}-grpc
  labels:
    app: {{ .Values.auth.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.auth.name }}
  ports: 
    - name: grpc
      protocol: TCP
      port: {{ .Values.auth.port.grpc }}
      targetPort: {{ .Values.auth.port.grpc }}
{{- end }}