{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name}}-grpc
  labels:
    app: {{ .Values.auth.name}}
spec:
  selector: ClsuterIP
    app: {{ .Values.auth.name}}
  ports: 
    - protocol: TCP
    - port: {{ .Values.auth.port.grpc}}
      targetPort: {{ .Values.auth.port.grpc}}
{{- end}}