
# {{- if .Values.auth.enabled }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.auth.name}}-http
#   labels:
#     app: {{ .Values.auth.name}}
# spec:
#   selector: ClusterIP
#     app: {{ .Values.auth.name}}
#   ports: 
#     - protocol: TCP
#     - port: {{ .Values.auth.port.http}}
#       targetPort: {{ .Values.auth.port.http}}
# {{- end}}