{{- if .Values.products.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.products.name}}-grpc
  labels:
    app: {{ .Values.products.name}}
spec:
  selector: ClusterIP
    app: {{ .Values.products.name}}
  ports: 
    - protocol: TCP
    - port: {{ .Values.products.port.grpc}}
      targetPort: {{ .Values.products.port.grpc}}
{{- end}}