{{- if .Values.executor.enabled}}
apiVersion: v1
kind: Deployment
metadata:
  name: {{ .Values.executor.name}}
  labels:
    app: {{ .Values.executor.name}}
spec:
  replicas: {{ .Values.executor.replicas}}
  selector: 
    matchLabels:
      app: {{ .Values.executor.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.executor.name}}
    spec:
      containers:
        - name: {{ .Values.executor.name}}
          image: {{ .Values.executor.image}}
          imagePullPolicy: {{ .Values.global.imagePullPolicy}}
          ports:
            - containerPort: {{ .Values.executor.port}}
          env:
            {{- include "common.env" . | nindent 12}}
            - name: PORT
              value: {{.Values.executor.port}}
            - name: JOBS_GRPC_SERVICE_PORT
              value: "{{ .Values.jobs.name}}-grpc:{{ .Values.jobs.port.grpc }}"
            - name: PRODUCTS_GRPC_SERVICE_PORT
              value: "{{ .Values.products.name}}:{{ .Values.products.port.grpc }}"
{{- end}}