// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v4.25.1
// source: products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export interface CreateProductRequest {
  name: string;
  category: string;
  price: number;
  stock: number;
  rating: number;
  description: string;
}

export interface CreateProductResponse {}

export interface CreateProductManyRequest {
  products: CreateProductRequest[];
}

export interface CreateProductManyResponse {
  responses: CreateProductResponse[];
}

export interface ProductsServiceClient {
  createProduct(
    request: CreateProductRequest
  ): Observable<CreateProductResponse>;

  createProductMany(
    request: CreateProductManyRequest
  ): Observable<CreateProductManyResponse>;
}

export interface ProductsServiceController {
  createProduct(
    request: CreateProductRequest
  ):
    | Promise<CreateProductResponse>
    | Observable<CreateProductResponse>
    | CreateProductResponse;

  createProductMany(
    request: CreateProductManyRequest
  ):
    | Promise<CreateProductManyResponse>
    | Observable<CreateProductManyResponse>
    | CreateProductManyResponse;
}

export function ProductsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['createProduct', 'createProductMany'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcMethod('ProductsService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcStreamMethod('ProductsService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
  };
}

export const PRODUCTS_SERVICE_NAME = 'ProductsService';
